### ISSUE TITLE
Run gnomad QC test in jupyter notebook for gks-pilot API changes

### ISSUE THREAD

**Issue by larrybabb** [ga4gh/va-spec#102]
@theferrit32 will produce a jupyter notebook that demonstrates that the 10-20 expected json statements match the results returned from the forthcoming gnomad api changes for this project.  This depends on #101 .

**Comment by theferrit32** [comment]
Adding a notebook alongside the qc one that uses the bulk annotation functions I added in https://github.com/broadinstitute/gnomad_methods/pull/559
