### ISSUE TITLE
Should Extension inherit from ExtensibleEntity?

### ISSUE THREAD

**Issue by mbrush** [ga4gh/va-spec#108]
IMO we want Extensions themselves to be extensible (e.g. as they are in FHIR). If this is the case, we should make the [Extension class](https://github.com/ga4gh/gks-metaschema/blob/main/tests/data/core-source.yaml#L98) inherit from ExtensibleEntity in the core-source.yaml file.

**Comment by larrybabb** [comment]
@mbrush  I don't agree with adding this complexity until we have an implementer that asks for it. It is not necessary at this time so I would suggest we archive this discussion and re-raise if/when it is requested for an implementer's use case.
@mbrush  I will defer to you to close this for now if you agree. So we can get our issue list down to the most pertinent issues.

**Comment by mbrush** [comment]
Hi @larrybabb - this ticket is quite old, and was written when there was an `ExtensibleEntity` class in the model. There is not anymore, and the `extension` property is now defined on `Entity`.  

So the relevant questions now are: 
- Do we want `Extensions` to be extensible? 
   - I see value in permitting this - give users flexibility that efforts like FHIR have deemed useful enough to include in their model.  But I am ok with passing on this for now as you suggest - until it requested by an implementer. 

- If we do want `Extensions` to be extensible, we either need to have them inherit from `Entity`, or define an `extensions` field on them directly.  
    - I would prefer the latter (I don't think Extensions need all the other properties defined on `Entity`).  But again, this second question is only relevant if the answer to the first question is 'yes'

I will go ahead and close this ticket - but others can re-open if/when they want to explore this more.
