### ISSUE TITLE
Should the Expression class inherit from Extensible Entity? 

### ISSUE THREAD

**Issue by mbrush** [ga4gh/va-spec#109]
'Expression' is defined in the vod-source.yaml file. IMO this is a generally useful class that should be defined in the same place as things like Coding, Extension, etc.  (i.e. in the core-source.yaml file) . . . and that here it could inherit from ExtensibleEntity.

**Comment by larrybabb** [comment]
@mbrush  I think we discussed the value of Expression and distinguished it from Extensible over the past few weeks. As a result we moved `Expresssion` to gks-common. So I will assume this is no longer an issue and close it. Please reopen and raise any additional concerns that I may be missing.
