### ISSUE TITLE
Upgrade hail function for gnomad vrs api for 'cohort' name changes

### ISSUE THREAD

**Issue by larrybabb** [ga4gh/va-spec#112]
Change population... to cohort... in all field names and modify the focusAllele values to be "#/focusAllele".

Create a pull request for the gnomad team since they are unable to get to this in the near term. We hope they will be able to merge this PR.

This should ungate the testing task since Kyle can reference the PR before or after it is merged.

**Comment by theferrit32** [comment]
Completed in https://github.com/broadinstitute/gnomad_methods/pull/559
