### ISSUE TITLE
Add heterozygous allele balance flag to gnomad annotations

### ISSUE THREAD

**Issue by theferrit32** [ga4gh/va-spec#117]
There's a `quality_metrics.allele_balance.bin_freq` somewhere that might be an array. It represents 5 percentile buckets of counts of samples with different allele balance scores. The last two buckets (.9, .95) and (.95, 1) are used in determining whether a flag should be displayed. If the sum of those two buckets are nonzero, a flag is displayed with the sum. 

If exomes and genomes are available, each should be summed and displayed independently.

**Comment by theferrit32** [comment]
The field in the hail table appears to be: `.raw_qual_hists.ab_hist_alt.bin_freq`. 

See `ab_hist_alt` section here: https://gnomad.broadinstitute.org/help/hgdp-1kg-annotations

I'm checking a couple records to match them to the UI and have some confusion.

Some of the values do match, but for example in `1-629844-A-G`, the 1 in index 2 (0 based) is not in the histogram but all the other values are.

## `1-629844-A-G`
ab bin freq: `[0,0,1,0,1,0,0,0,1,1,1,3,0,0,0,0,0,1,0,0]`
The histogram on https://gnomad.broadinstitute.org/variant/1-629844-A-G?dataset=gnomad_r3
<img width="550" alt="Screenshot 2023-10-04 at 12 08 08 AM" src="https://github.com/ga4gh/va-spec/assets/2839238/dd21f2b9-5334-4b4a-b81c-fa87aff0f24e">

## `1-633440-A-ATCCC`
ab bin freq: `[0,1,0,0,0,0,0,0,1,0,1,0,0,1,0,0,0,0,0,0]`
The histogram on https://gnomad.broadinstitute.org/variant/1-633440-A-ATCCC?dataset=gnomad_r3
<img width="549" alt="Screenshot 2023-10-04 at 12 10 42 AM" src="https://github.com/ga4gh/va-spec/assets/2839238/822d3a2f-e49a-4f87-83a3-e1a60694cb99">

**Comment by theferrit32** [comment]
Looking at `1-633440-A-ATCCC` there are two 1's in the ab bin freq array that are missing from the histogram. The one at index 1 and at index 13.

I can grab the network request that drives this UI element though and the array is different than the one I got from the hail table. (Under `quality_metrics.allele_balance.alt.bin_freq`)

<img width="311" alt="Screenshot 2023-10-04 at 12 15 56 AM" src="https://github.com/ga4gh/va-spec/assets/2839238/5c4f4f9d-6751-4d67-a5b0-71875be0032e">

```
[0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0] (API response to UI)
[0,1,0,0,0,0,0,0,1,0,1,0,0,1,0,0,0,0,0,0] (in hail table)
```

**Comment by theferrit32** [comment]
Resolved this. Looked at the browser code and it's referring to `.qual_hists.ab_hist_alt.bin_freq` which excludes low quality samples.

**Comment by theferrit32** [comment]
https://github.com/broadinstitute/gnomad_methods/compare/main...theferrit32:gnomad_methods:kf/gks-cg-annotations

@larrybabb  example with variant qc flags, allele balance flag, and low complexity region:

```json
{
  "locus": {
    "contig": "chr1",
    "position": 4807634,
    "reference_genome": "GRCh38"
  },
  "alleles": [
    "TAAAA",
    "T"
  ],
  "gks_vrs_variant": {
    "_id": "ga4gh:VA.daK3dsUv6m3WLMDpdSYcWUw5Spo-jwgB",
    "type": "Allele",
    "location": {
      "type": "SequenceLocation",
      "sequence_id": "ga4gh:SQ.Ya6Rs7DHhDeg7YaOSg1EoNi3U_nQ9SvO",
      "interval": {
        "start": {
          "type": "Number",
          "value": 4807634
        },
        "end": {
          "type": "Number",
          "value": 4807659
        },
        "type": "SequenceInterval"
      },
      "_id": "ga4gh:VSL.hcL2_ScoNOE8rHdZdHRZjRS22464N1eV"
    },
    "state": {
      "type": "LiteralSequenceExpression",
      "sequence": "AAAAAAAAAAAAAAAAAAAAA"
    }
  },
  "gks_va_freq": {
    "id": "gnomAD-3.1.4-chr1-4807634-TAAAA-T",
    "type": "CohortAlleleFrequency",
    "label": "Overall Cohort Allele Frequency for chr1-4807634-TAAAA-T",
    "derivedFrom": {
      "id": "gnomAD3.1.4",
      "type": "DataSet",
      "label": "gnomAD v3.1.4",
      "version": "3.1.4"
    },
    "focusAllele": {
      "_id": "ga4gh:VA.daK3dsUv6m3WLMDpdSYcWUw5Spo-jwgB",
      "type": "Allele",
      "location": {
        "type": "SequenceLocation",
        "sequence_id": "ga4gh:SQ.Ya6Rs7DHhDeg7YaOSg1EoNi3U_nQ9SvO",
        "interval": {
          "start": {
            "type": "Number",
            "value": 4807634
          },
          "end": {
            "type": "Number",
            "value": 4807659
          },
          "type": "SequenceInterval"
        },
        "_id": "ga4gh:VSL.hcL2_ScoNOE8rHdZdHRZjRS22464N1eV"
      },
      "state": {
        "type": "LiteralSequenceExpression",
        "sequence": "AAAAAAAAAAAAAAAAAAAAA"
      }
    },
    "focusAlleleCount": 51467,
    "locusAlleleCount": 90458,
    "alleleFrequency": 0.5689601804152203,
    "cohort": {
      "id": "ALL"
    },
    "ancillaryResults": {
      "homozygotes": 13498,
      "popMaxFAF95": {
        "frequency": 0.6498521500000005,
        "confidenceInterval": 0.95,
        "popFreqID": [
          "chr1-4807634-TAAAA-T.NFE"
        ]
      },
      "qcFilters": [
        "AS_VQSR"
      ],
      "lowComplexityRegion": true,
      "heterozygousAlleleBalanceFlagged": 65,
      "meanDepth": 12.622911494797913
    }
  }
}

```

**Comment by larrybabb** [comment]
@theferrit32 you da man

**Comment by theferrit32** [comment]
Renamed field to `heterozygousSkewedAlleleCount`. Closing as completed.
