### ISSUE TITLE
Release downsampled gnomad v4 and gk-pilot CohortAlleleFrequency annotations

### ISSUE THREAD

**Issue by theferrit32** [ga4gh/va-spec#118]
Update: we are going to do this for v4 instead of v3. We need a downsampled v4 table once they are done changing things.

Initial thought is to put these in a bucket

```
gk-pilot/
    gnomad_v3.1.4_downsampled_100k.ht/
    cohort_allele_frequency.ndjson
```

The gnomad annotation functions don't actually annotate the table, they return the annotations in a python dict. With a little work I could take those and add them to each row in the table as JSON strings.

**Comment by larrybabb** [comment]
@theferrit32 what is the status of this? do we still need it?

**Comment by larrybabb** [comment]
@theferrit32 please weigh in on whether or not this should be closed. I think this is done, but not 100%.

**Comment by theferrit32** [comment]
@larrybabb this is done, we did this temporarily while waiting for the annotations to be added to the official v4 tables
