### ISSUE TITLE
Need new diagnostic/prognostic models that work with VRS 2.0

### ISSUE THREAD

**Issue by wesleygoar** [ga4gh/va-spec#127]
@ahwagner we need new diagnostic/prognostic models that will work with VRS 2.0.

**Comment by ahwagner** [comment]
The following are for CIViC _Evidence_ objects.

### Therapeutic Response
Modify the [VariantTherapeuticResponseStudy](https://github.com/ga4gh/va-spec/blob/fd4a5f2f7bb433a69867c31bc3feca90a2f00239/schema/va-spec/profiles/t-resp/t-resp-source.yaml#L22-L82):
- rename `tumorType` to `disease`
  - revise definition of `disease` to "The **disease** ~tumor type~ context in which..."

### Diagnostic
Start with the modified VariantTherapeuticResponseStudy and make the following changes:
- Class name is `VariantDiagnosticStudy`
- Update description to: "A study summarization describing whether a variant is associated with a disease (positive) or lack of a disease (negative)."
- Drop therapeutic property
- Drop the `disease` property
- Add a new `disease` property
  - extends `object` (the VA notion of `object`)
  - initial definition as "the disease that is evaluated for presence"
- revise predicates to `positive` and `negative`

### Prognostic
Start with the above VariantDiagnosticStudy and make the following changes:
- Class name is `VariantPrognosticStudy`
- Update description to: "A study summarization describing whether a variant is associated with improved or worse outcome for a disease."
- Revise the `disease` property definition as "the disease that is evaluated for outcome"
- revise predicates to `Improved Outcome` and `Worse Outcome`
  - *NOTE*: This is not consistent with the CIViC predicates, which are Better Outcome / Poor Outcome/ "N/A"

**Comment by ahwagner** [comment]
@korikuzma see requirements above. Let me know if you have any questions. Thank you for taking this on!

**Comment by korikuzma** [comment]
@ahwagner created a draft PR and had one question from your requirements: https://github.com/ga4gh/va-spec/pull/145/files#r1628473160

**Comment by korikuzma** [comment]
@ahwagner I also made other comments on #145
