### ISSUE TITLE
Update indefinite range to use integers

### ISSUE THREAD

**Issue by hdziadzio** [ga4gh/va-spec#129]

**Comment by hdziadzio** [comment]
Kyle needs to do analysis and add description

**Comment by theferrit32** [comment]
Updating the field IndefiniteRange.value in CohortAlleleFrequency requires:
- [x] make change to `vrs-source.yaml` in `vrs`  and rebuild schemas using makefile (https://github.com/ga4gh/vrs/pull/498)
- [ ] change the version of `vrs @ 1.x` depended on by `cat-vrs @ 1.x` as a submodule
- [ ] change the version of `cat-vrs @ 1.x` depended on by `va-spec @ 1.x` as a submodule

**Comment by larrybabb** [comment]
@theferrit32 I just went through and updated all the submodules across GKS so that va-spec now points to VRS 2.x's latest commit (as of today).  So I think this ticket can be closed.

Please review and let me know if there's more needed here. otherwise please close this.
