### ISSUE TITLE
Fix typo for Characterisitc model

### ISSUE THREAD

**Issue by korikuzma** [ga4gh/va-spec#149]
Characterisitc should be changed to Characteristic

**Comment by mbrush** [comment]
@korikuzma Thanks for addressing this and other typos - and sorry for my sloppy edits that put them there.  I am used to working in text editing environments that highlight such mistakes!  Will be more vigilant in the future.

**Comment by korikuzma** [comment]
@mbrush No worries! I use VS Code and have the [Code Spell Checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker) extension installed.
