### ISSUE TITLE
Why isn't 'alleleOrigin' defined as an optional qualifier in the VarPath Statement profile?

### ISSUE THREAD

**Issue by mbrush** [ga4gh/va-spec#163]
I see an `alleleOriginQualifier` on all other Variation Statement profiles. Seems like it could be applied to Var Path statements, so why not include it as an option?  Is it just because you are not yet populating this info for the ClinVar implementation that is driving this initial profile?

**Comment by larrybabb** [comment]
The data in clinvar related to this is all over the place, so we will put this in as an extension. Their really should never be anything other than 'germline' in a VarPath alleleOrigin value. Regardless, it does not impact the outcome of the classification in any way (at least the way it is ignored in clinvar).  

If I come across a need for this as a formal Qualifier I will add it back then.
