### ISSUE TITLE
Consistent use of 'Condition' (vs 'Disease')

### ISSUE THREAD

**Issue by mbrush** [ga4gh/va-spec#188]
Noting that we use both terms 'condition' and 'disease' in attribute names and class/attribute descriptions, across the different statement profile files.  I assume that the inconsistent use of the terms in attribute names and class/attribute descriptions across various profiles is unintentional. 

I recommend that we update these to use the broadest term  'condition' in all cases (unless there is reason to sue a more specific term like 'disease' or 'tumor') - so that we are clear and consistent here.  Esp since our model makes an explicit distinction between `Condition` and `Disease` classes.

**Comment by larrybabb** [comment]
I agree with the recommendation. To be clear though, the term `Condition` is specifically defined to be either a `Disease` a `Phenotype` or a `TraitSet`. And a `TraitSet` is a term from clinvar that can be 2 or more items of a `Disease` and/or `Phenotype`.  If we are going to do any major redefining of `Condition` let's coordinate this with the clinvar implementation so we do not break it.

**Comment by mbrush** [comment]
Hi Larry.  This is how I understand things as well.  I will make a PR with updates to labels and text to be consistent with the modeling. 

If this requires downstream work to update data or models - we can wait to push this until after the Connect meeting.

**Comment by larrybabb** [comment]
I think we've sorted this out with the latest `Condition`, `TraitSet` domain-entities in VA-spec.
