### ISSUE TITLE
Are submods specified correctly?

### ISSUE THREAD

**Issue by mbrush** [ga4gh/va-spec#194]
See https://github.com/ga4gh/va-spec/blob/1.x/schema/core-im

This submodule points to the core-im with the following path:

`../submodules/cat-vrs/schema/core-im`

Why is cat-vrs in the path?  Shouldn't this get the core-im from the gks-common repo, with a path like:

`../submodules/gks-common/schema/core-im`

I ask because as I build the va-spec RTD documentation in the va-spec repo, I need to pull in autogenerated Class .rst files like [this one](https://github.com/ga4gh/gks-common/blob/1.x/schema/core-im/def/Statement.rst) from the gks-common repo - through the submodule - to populate content in the va-spec RTD pages.

**Comment by korikuzma** [comment]
@mbrush I believe it is pointing to cat-vrs because gks-common is a submodule in cat-vrs and va-spec has cat-vrs as a submodule, but not gks-common as a submodule.

**Comment by mbrush** [comment]
OK, interesting . . . . can you help me figure out how to pull a Class .rst file from the gks-common repo - through these submodules - to populate content in the va-spec RTD pages?  For example, I want to populate the [va-spec doc page here](https://github.com/ga4gh/va-spec/blob/1.x/docs/source/core-information-model/entities/information-entities/dataset.rst) with  [this gks-common .rst file](https://github.com/ga4gh/gks-common/blob/1.x/schema/core-im/def/DataSet.rst)?  

I tried this by writing the following 'include' directive through submods:

````
.. include::  ../../../../../schema/core-im/def/DataSet.rst
````

. . . but likely did it wrong as it is not populating. Thanks!

**Comment by korikuzma** [comment]
@mbrush seems to be populating correctly when I look at it locally! 

![Screenshot 2024-09-05 at 10 38 07](https://github.com/user-attachments/assets/bb566b3c-5d9a-46b6-aeb5-937056ab5fab)

**Comment by korikuzma** [comment]
@mbrush I ran:

```
cd docs
make clean watch &
```

and then opened `docs/build/html/index.html`. 

When you try this locally, are you able to see it populated?

**Comment by mbrush** [comment]
Huh . . . and to confirm, do you see this in the web version of the doc here:  https://va-ga4gh.readthedocs.io/en/stable/core-information-model/entities/information-entities/dataset.html? 

Any idea why it would work locally but not on the web?

**Comment by korikuzma** [comment]
@mbrush I'm not sure how RTD deployment is set up. Has a new release been made for the 1.x branch?

**Comment by larrybabb** [comment]
@mbrush I believe this has been rectified. I see the rendered DataSet page you reference in the link above. Please close this if it is addressed or add additional information about the issue.

**Comment by mbrush** [comment]
fixed
