### ISSUE TITLE
Variant pathogenicity statements should have a classification

### ISSUE THREAD

**Issue by Mrinal-Thomas-Epic** [ga4gh/va-spec#208]
Variant pathogenicity is reported using classification terms like "Pathogenic", "Benign", etc. There used to be a property for this, but I can no longer find it.

**Comment by ahwagner** [comment]
Do you mean as an enum? I see the classification field [here](https://github.com/ga4gh/va-spec/blob/e81426fbcf958ebc5835d3dc4d9b4b6159b9b510/schema/profiles/json/VariantPathogenicityStatement#L126-L135), for example. Though this has been turned into a `Coding` and some examples where such a code is provided would be helpful. And if a coding doesn't exist, it might be worth recreating the `Mappable Entity` class that allowed for non-coded entities so they may be representable as strings.

**Comment by Mrinal-Thomas-Epic** [comment]
The property you linked to seems like a good approach to me. I couldn't find the property in the `1.0.0-connect.2024-09` schema for va-spec (or `gk-pilot` main), so I was trying to use this issue to ask, where did it go in the pre-release?

Edit: I see it in the JSON schema in the `1.0.0-connect.2024-09`, just don't see where its coming from in the source yaml

**Comment by Mrinal-Thomas-Epic** [comment]
Nevermind, I see it now in `core-im-source.yaml`. Although I am curious why its on all statements, rather than a special type of `ClassificationStatement` like before

**Comment by ahwagner** [comment]
I think that @mbrush and @larrybabb flattened a lot of the VA Spec abstract classes in their rework leading up to Connect. 

I agree that the "Statement" class doesn't seem like a great fit for the classification attribute, and this is a decision I would also like some additional clarity / refinement on.
