### ISSUE TITLE
Does Trait Set definition need to be specific to Var Path Statements?

### ISSUE THREAD

**Issue by mbrush** [ga4gh/va-spec#231]
In https://github.com/ga4gh/va-spec/edit/mbrush-description-text-updates/schema/va-spec/base/domain-entities-source.yaml, do we need to define the trait set as being in the context of a VP statement?  Same for therapeutic, and therapy group, in the context of a TR study statement

**Comment by larrybabb** [comment]
i did not mean to make it VP statement specific. Please correct/fix/edit.

**Comment by ahwagner** [comment]
I believe this was addressed; please reopen if not.
