### ISSUE TITLE
Include (and require value for) a predicate field in all statement types

### ISSUE THREAD

**Issue by mbrush** [ga4gh/va-spec#66]
At present we don not include a predicate attribute for VA statements where there is only a single predicate possible, which can be intuited from the type of statement (e.g. for MC Annotations, where the predicate is simple 'has_consequence').  However, it has been suggested that including the predicate attribute and making it required (1..1) would result in more consistent and parsable/computable data - even though it adds no discriminatory value. 

This ticket is to capture feedback on this proposal. 

Other VA Statement types where there is currently no predicate attribute in the statement model include Population Frequency and Computational Functional Impact.

**Comment by larrybabb** [comment]
This is no longer relevant.  We moved predicate to `Proposition` and require it
