### ISSUE TITLE
Resolve changes from coding and ID discussion

### ISSUE THREAD

**Issue by ahwagner** [ga4gh/va-spec#73]
1. Change `LabeledEntity` to `Coding`
2. Change domain entity IDs to `id`

**Comment by mbrush** [comment]
@larrybabb @ahwagner @tnavatar I updated the VA-Core 'Coding' class to reflect changes we discussed - including changing the 'code' field to 'id', and recommending use of CURIE format for identifiers. See updated 'Coding' schema [here](https://docs.google.com/document/d/18vBMg6nl7S1rAUCSoybo8ONeNGK5ObuV2WhDhZJBmLg/edit?pli=1#heading=h.xh1x6kkd6fa3).  A couple things to note:

1. For now I stopped short of _formally requiring_ a CURIE as the id - instead referencing the VA '[identifier](https://docs.google.com/document/d/18vBMg6nl7S1rAUCSoybo8ONeNGK5ObuV2WhDhZJBmLg/edit?pli=1#heading=h.rd6b8f57f4k2)' data type (where our documentation STRONGLY recommends use of CURIES for structuring identifiers).  The idea is to not introduce barrier to adoption for users who may not have/want to create or use curies initially.  But in the future we will likely define/adopt a formal 'curie' data type and require its use here.  Just wasn't ready to fully commit to this when I put out the initial v0 doc.

3. I left in the 'system', 'system_url', and 'system_version' fields for now - as these can still provide additional structured info about the code system that provided a curie.  But they are optional, and we can remove them if we wish.

**Comment by larrybabb** [comment]
Thanks @mbrush looks good, but...
I see now that you have the attribute name `identifier` and we use `id` in VRS and VRSATILE. We are considering change  `_id` in VRS objects to `id` in v2. However, in either case the nested `identifiable` entities in VRS do impact the computed digests, so I'm not sure we can change to `identifier` for the attribute name.

I recognize that FHIR has both `id` and many times (but not always) `identifier` on all of their resources (not on meta, complex and primitive data types though). The `id` field in FHIR is used for in-message references and can use a business `identifier` or a temporary/transient message-level value that only needs to be unique within the message. 

We (VRS) are not taking the approach of including both `id` and `identifier` on any of our structures. I do think all `Entity` types should have an `id` to support the in-message referencing of concepts, and I do think we can share real `identifiers` this way, but we are not planning on using the `identifier` slot and name anywhere.

Let us know if this is a concern and how we should deal with this going forward.

**Comment by mbrush** [comment]
@larrybabb can you tell me how you would recommend a data creator transmit 'business identifiers' for an entity represented in their data?  e.g. if they create a local / logical id for a Condition object, but also want to pass community-based 'business' identifiers for the Condition in their message?    This as I understand is the primary use case for FHIR identifiers.  

I suspect that in GKS models, any additional public identifiers for the Condition would get captured in the a Descriptor object that references the Condition value object, correct? However I don't see a field in the VRSATILE 'ValueObjectDescriptor' class for this purpose  (xref is the closest one).

**Comment by larrybabb** [comment]
good question. I do think that business identifiers should be passed in the `XXXDescriptor` objects only. Your observation that `xref` is the closest available option. Like, FHIR Resources, we could add and explict `identifier` field that allows folks to add one or more business identifiers that the sender considers a precise representation of the concept in a potentially available repository. Or we could just use `xref` for now and assume that the identifiers within `xref` are all forms of similar or exact matching business identifiers.  I'm not 100% sure I've seen the use case yet. I do think it will come to bear that we will need an `exact match` flag on the `xref`s (similar to what MONDO does) or create a separate `identifier` attribute to be exact matching `xref`s.

**Comment by larrybabb** [comment]
We (Clingen) is adding an attribute called `is_version_of` to our statements and descriptors that represent versions of concepts from authorities like ClinVar.  For example, the SCV accession id for a clinvar submission is a very important attribute to identify the concept of a variation submission from submitter and it's various versions over time.  Yet we really don't have an explicit representation of the SCV concept only versions of it.  So, SCV123.1 and SCV123.2 are conceptually based on the submitter's desire to make a statement about the pathogenicity of a given variant, but they may modify that statement over time.  We will have both SCV123.1 and SCV123.2 entity statements in our system, that both have an attribute called `is_version_of` that represents the core concept of the submitter's submission _SCV123_.

**Comment by ahwagner** [comment]
Summary of planned changes:

- Change domain entity id fields to `id`
- Require `id` to be CURIE for ValueEntities, but relax constraint to any string for other Entities
- Change `LabeledEntity` to `Coding`

Note: `is_version_of` as described by @larrybabb is already implemented in our RecordMetadata class and there are no planned changes to that class, nor are there plans to use `identifier` or `code` elsewhere. This ticket will be closed once these planned changes are implemented. Please feel free to re-open this ticket if there are demonstrable use cases that are not covered by these changes.

**Comment by ahwagner** [comment]
Addressed in https://github.com/ga4gh/vrs/commit/54799fa3f1dd386447f7ea1c2455c5f2693e4bca.
